site_name: Strawberry Django +
site_description: Strawberry-Django extra features
#site_url: https://nrbnlulu.github.io/strawberry-django-auth/
site_author: community
repo_name: strawberry-django-plus
repo_url: https://github.com/blb-ventures/strawberry-django-plus/

theme:
  name: material
  language: en
  palette:
  - scheme: default
    primary: purple
    accent: indigo
    toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  - scheme: slate
    primary: black
    accent: purple
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode



  logo: images/logo.png
  favicon: images/logo.svg
  features:
    - content.code.annotate
extra:
#  analytics:
#    provider: google
#    property: G-XYFSBNLH00
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/blb-ventures/strawberry-django-plus/issues" target=_blank>posting an issue</a>.

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.superfences
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - markdownextradata:
        data: docs/data

dev_addr: 127.0.0.1:7000

nav:
  - Start here: index.md
  - Quick start: QuickStart.md
  - Extensions:
       - Query optimizer: QueryOptimizer.md
  - Contributing: Contributing.md