# Generated by Django 4.0.1 on 2022-01-09 19:09

from django.db import migrations, models
import django_choices_field.fields

import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=django_choices_field.fields.TextChoicesField(  # type:ignore
                choices=[("active", "Active"), ("inactive", "Inactive")],
                choices_enum=tests.models.Project.Status,
                default="active",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(help_text="The name of the project", max_length=255),
        ),
    ]
