# Generated by Django 4.1.2 on 2022-11-03 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("demo", "0002_tag_remove_milestonecomment_milestone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "sequence",
                    models.PositiveIntegerField(default=1, unique=True, verbose_name="sequence"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignee",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("owner", models.BooleanField(default=False)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_assignees",
                        related_query_name="issue_assignee",
                        to="demo.issue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_assignees",
                        related_query_name="issue_assignee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="issue",
            name="assignees",
            field=models.ManyToManyField(
                related_name="+", through="demo.Assignee", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
