# Generated by Django 4.1.3 on 2022-12-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_quiz_assignee_issue_assignees"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="milestone_not_null",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues_additional",
                related_query_name="issues_additional",
                to="demo.milestone",
            ),
        ),
    ]
