# Generated by Django 4.2 on 2023-04-04 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0004_issue_milestone_not_null"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="milestone_not_null",
        ),
    ]
