name: docs deploy


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: make deploy-docs
      - run: python -m mkdocs gh-deploy --force
