---
name: 🆕 Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - release/**

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: extract_branch
        name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          default-branch: ${{ steps.extract_branch.outputs.branch }}
          package-name: strawberry-django-plus
          extra-files: strawberry-django-plus/__init__.py
          bootstrap-sha: cb311899f3bd6dd36fd6017a511bcac9f7011e07
          changelog-types: >
            [{"type":"feat","section":"Features","hidden":false},
             {"type":"fix","section":"Bug Fixes","hidden":false},
             {"type":"perf","section":"Performance","hidden":false},
             {"type":"deps","section":"Dependencies","hidden":false},
             {"type":"revert","section":"Reverts","hidden":false},
             {"type":"docs","section":"Documentation","hidden":false},
             {"type":"style","section":"Styles","hidden":false},
             {"type":"refactor","section":"Code Refactoring","hidden":false},
             {"type":"test","section":"Tests","hidden":false},
             {"type":"build","section":"Build System","hidden":false},
             {"type":"ci","section":"Continuous Integration","hidden":false},
             {"type":"chore","section":"Miscellaneous","hidden":false}]
      - if: ${{ steps.release.outputs.release_created }}
        name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
